### ISSUE TITLE
cvtColor error

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/eynollah#128]
In #108 we recently (probably because of a new OpenCV release) started to see this error:
```
INFO eynollah - INPUT FILE df_ld_0022741 (11/12) 
OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

INFO eynollah - Resizing and enhancing image...
```

I checked all places where `cv2.cvtColor` is used, and AFAICS it always gets passed a Numpy array. Unfortunately, OpenCV does not show the exact stack trace...

**Comment by vahidrezanezhad** [comment]
@bertsky 
Could you please share the input file? And does this happen in the OCR-D pipeline or in the standalone Eynollah?

**Comment by bertsky** [comment]
Oops, sry, my local branch already had a few more commits I forgot about, which exposed a problem with `check_dpi`.

See https://github.com/qurator-spk/eynollah/pull/108/commits/60cf0bddfd35dd3fcd87b2e077b05bb170983977

(IOW the type checking for PIL.Image was wrong, which had the conditional enter the branch expecting an array)

Would you like me to make a cherry-picked PR for this fix?

**Comment by vahidrezanezhad** [comment]
> Oops, sry, my local branch already had a few more commits I forgot about, which exposed a problem with `check_dpi`.
> 
> See [60cf0bd](https://github.com/qurator-spk/eynollah/commit/60cf0bddfd35dd3fcd87b2e077b05bb170983977)
> 
> (IOW the type checking for PIL.Image was wrong, which had the conditional enter the branch expecting an array)
> 
> Would you like me to make a cherry-picked PR for this fix?

Yes, sure.

**Comment by bertsky** [comment]
Oh, wow! I just realised that I had _already fixed this_ in https://github.com/qurator-spk/eynollah/commit/867a7261de27bec7efc7e7add80f10ae18bc419a. 

But somehow, I seemed to have forgot including #109 in #108.
