### ISSUE TITLE
TextLine coordinates too coarse

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/eynollah#14]
This is [the same issue](https://github.com/qurator-spk/sbb_textline_detection/issues/33) reported for the predecessor sbb_textline_detection before: region contours are fine-grained, tight polygons, but text lines are coarse bounding boxes that expand way beyond their parent region and overlap between neighbours.

Example:
![FILE_0002_ORIGINAL_pageviewer-detail](https://user-images.githubusercontent.com/38561704/106315269-4e52bd00-626b-11eb-8e18-c98cc9d6a4a1.png)

Now, I understood the author as [saying](https://github.com/qurator-spk/sbb_textline_detection/issues/33#issuecomment-667349891) that this will _not_ happen in eynollah. But he also said there's a performance trade-off. So can I enable the fine-grained text line contours somewhere?

Although I have not looked into the code yet, maybe my [previous fix](https://github.com/qurator-spk/sbb_textline_detection/pull/48) would apply here, too? (Yes, I do know extracting text line contours is more involved than just intersecting with the parent – especially separating neighbours. Still...)

**Comment by vahidrezanezhad** [comment]
Dear Robert, If you use cl option you will get contour for textlines.

**Comment by bertsky** [comment]
> So can I enable the fine-grained text line contours somewhere?

My apologies! I initially used `-cl` but this time completely forgot about it. Here's the proper result:

![FILE_0002_ORIGINAL_pageviewer-detail](https://user-images.githubusercontent.com/38561704/106317121-1a2ccb80-626e-11eb-8e93-a58fec596426.png)

This is very good indeed! (I wonder whether we now should rather try to expand the regions to the convex hull of their constituent lines...)

**Comment by bertsky** [comment]
> Dear Robert, If you use cl option you will get contour for textlines.

Dear Vahid – thanks, just saw my mistake!
