### ISSUE TITLE
Paper reference

### ISSUE THREAD

**Issue by sufihimalaya** [qurator-spk/eynollah#25]
Hello, I was wondering if I could refer to this project on my paper.
I would like to know if there is any publicized research papers this project is based on, especially the text line detection part?

Thanks!

**Comment by cneud** [comment]
A paper about Eynollah has now been accepted at [HIP'23](https://blog.sbb.berlin/hip2023/) and will appear in August 2023. The citation information has already been added to the readme: https://github.com/qurator-spk/eynollah#how-to-cite.
