### ISSUE TITLE
How to get Image segment as img as Shown in repo for newspaper cutting

### ISSUE THREAD

**Issue by dhirendraAL** [qurator-spk/eynollah#27]
Hi Sir,
Can you pls tell the way I can get the result as segmented image that has mapped layouts with different color present in image. As the example you have displayed on the repo-https://user-images.githubusercontent.com/952378/102350683-8a74db80-3fa5-11eb-8c7e-f743f7d6eae2.jpg.
Thankyou

**Comment by kba** [comment]
the visualization is made by https://github.com/vahidrezanezhad/page-xml-to-image IIRC. You can also use the interactive https://github.com/PRImA-Research-Lab/prima-page-viewer to view PAGE-XML rendered.

**Comment by cneud** [comment]
The visualization can be done based on the resulting PAGE-XML file either with the tools that @kba linked or e.g. also https://github.com/GBN-DBP/page-xml-draw.

**Comment by vahidrezanezhad** [comment]
> Hi Sir,
> Can you pls tell the way I can get the result as segmented image that has mapped layouts with different color present in image. As the example you have displayed on the repo-https://user-images.githubusercontent.com/952378/102350683-8a74db80-3fa5-11eb-8c7e-f743f7d6eae2.jpg.
> Thankyou

You can also do this while running eynollah. Just enable plotting with -ep and then save the layout with -sl option. You can also apply -sa to get again the layout plot (again with -ep option)

**Comment by dhirendraAL** [comment]
Thankyou  for helping . Pls add these flag option to the repo so that it becomes easily accessible for others too.

**Comment by cneud** [comment]
Added in b3b49272a5bbd51e46629f6d6231c767100597e3, closing.
