### ISSUE TITLE
Multi class Instance Segmentation

### ISSUE THREAD

**Issue by ss756** [qurator-spk/eynollah#41]
Hi, 
    I would love to test out your pre-trained models on some documents. Could you point me to the right model to perform pixel wise region (text, image, separator) classification. Would be of gr8 help. 
Keep up the amazing work!!

**Comment by vahidrezanezhad** [comment]
Dear Suyash,

Eynollah uses a mixture of models based on the input and options wished by the user.  Eynollah by default can detect main texts, separators, images, background, and marginals.  If you are interested in headings and drop capitals you need to apply -fl option. Based on your source test dataset (if they are very dark or bright ) you can turn -ib (--input_binary) option. As you see based on the dataset and user-case Eynollah uses different models. You can share some of your documents and I may help you how you can use Eynollah to get optimum results :)

**Comment by ss756** [comment]
Sure that would be amazing. How can we get in touch or how can I send the documents I want to perform segmentation on ?

**Comment by vahidrezanezhad** [comment]
vahid631983@gmail.com this is my address. You can send me them here.

**Comment by ss756** [comment]
Thank you for replying I have sent an email please give it a look any help would be greatly appreciated

**Comment by cneud** [comment]
See also https://github.com/qurator-spk/eynollah#models.

**Comment by cneud** [comment]
The models and their names should then be shortly described in the models section of the README.
