### ISSUE TITLE
pip install . Fails because .json cannot be read properly.

### ISSUE THREAD

**Issue by IpsumDominum** [qurator-spk/eynollah#50]
Setting the version manually in setup.py works for me. But perhaps this should be changed.

**Comment by kba** [comment]
How do you mean "cannot be read properly" - what is the error message? And what platform are you installing it on?

**Comment by IpsumDominum** [comment]
Hi, nevermind! Somehow my .json file wasn't set up properly, I wasn't sure why :)

**Comment by kba** [comment]
OK good to hear it's working now. This might be because it's a symlink which isn't supported on e.g. Windows. Feel free to reopen if it happens in the future.
