### ISSUE TITLE
Inference stuck

### ISSUE THREAD

**Issue by ravilkashyap** [qurator-spk/eynollah#53]
I tried running this on google colab, took a decent 480p image and ran it against this tool but it gets stuck after image enhancement. Not sure if I'm doing anything wrong.

```
!eynollah -i "images/passport.jpg" -o "output/" -m "models_eynollah/"

18:17:58.077 INFO eynollah - resize and enhance image
18:17:58.077 INFO eynollah - Detected 96 DPI
18:18:17.683 INFO eynollah - Found 1 columns ([[1.00000000e+00 1.43745085e-11 3.50643126e-11 1.02011668e-14
  1.21690427e-11 8.64729710e-09]])
18:19:56.064 INFO eynollah - Image is enhanced
18:19:56.167 INFO eynollah - Enhancing took 118.0904438495636s 
18:20:03.120 INFO eynollah - Image dimensions: 448x672
18:22:48.668 INFO eynollah - Image dimensions: 448x672
```
It keeps running forever. 

Also, what is the inference time for an image?Thanks!

**Comment by vahidrezanezhad** [comment]
Dear @ravilkashyap ,

The inference time depends on the document. If you share the image I can help you more.

**Comment by cneud** [comment]
Hi @ravilkashyap, the inference time can be up to 10min (or more) for large, complex documents. For less challenging document images, we now also have a "light" version that significantly speeds up the inference, with little loss of quality in the detection. 

I am closing this, but feel free to re-open or file a new issue if the problems persist or when you have additional questions.
