### ISSUE TITLE
Irritating "Image dimension" log message

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/eynollah#55]
I am processing a 4000x6000 image using ocrd-eynollah-segment and get - among other messages - this message:
~~~
14:32:10.541 INFO eynollah - Image dimensions: 448x672
~~~

Should this read "Patch dimensions" and maybe get a log level of DEBUG?

**Comment by mikegerber** [comment]
👀 @vahidrezanezhad

**Comment by kba** [comment]
> maybe get a log level of DEBUG?

@vahidrezanezhad knows best about the contents but I converted all the `print` logging to `log.INFO`, so it's still visible in a default logging setup. These could certainly be more expressive and/or just be `DEBUG` stmts.

**Comment by cneud** [comment]
@vahidrezanezhad Can you please clarify/confirm what is the exact meaning of the log message here, i.e. whether  `Image dimensions: 448x672` does in fact refer to the size of the patches?

**Comment by vahidrezanezhad** [comment]
@cneud Yes. They are actually the patch size (input size) of each model.

**Comment by cneud** [comment]
Thanks. So let's change the log message accordingly for clarity then, ok?

**Comment by vahidrezanezhad** [comment]
sure

**Comment by mikegerber** [comment]
It should still be `DEBUG` not `INFO` though.

**Comment by mikegerber** [comment]
I've created PR #71 to downgrade the log message to loglevel `DEBUG`.
