### ISSUE TITLE
Textline Prediction Fine Tuning

### ISSUE THREAD

**Issue by frytoli** [qurator-spk/eynollah#69]
Firstly, thank you for this project! It's really cool.

I see in your README that you fine-tuned a previously trained textline detection model resulting in your final "newspaper textline" model. After digging into DH Segment's references, I believe the original model came from READ-BAD/[ARU-Net](https://github.com/TobiasGruening/ARU-Net) by Grüning et el. Correct? Given this information, could you give me some tips on how I might now be able to fine tune your textline detection model with my own dataset? Do you have any code you might be willing to share?

Thanks!

**Comment by vahidrezanezhad** [comment]
Dear Olivia,

"newspaper textline" model use a similar model structure as Dhsegment [https://github.com/dhlab-epfl/dhSegment ] but ours is deeper. And the encoder part is benefited from pre-computed weights. So in fact it is not fine-tuned from an older textline model..
You can train your own model or fine-tune our model using pixelwise segmentation [https://github.com/qurator-spk/sbb_pixelwise_segmentation].

**Comment by vahidrezanezhad** [comment]
Dear Olivia,

"newspaper textline" model use a similar model structure as Dhsegment [https://github.com/dhlab-epfl/dhSegment ] but ours is deeper. And the encoder part is benefited from pre-computed weights. So in fact it is not fine-tuned from an older textline model..
You can train your own model or fine-tune our model using pixelwise segmentation [https://github.com/qurator-spk/sbb_pixelwise_segmentation].[](Dear Olivia,

"newspaper textline" model use a similar model structure as Dhsegment [https://github.com/dhlab-epfl/dhSegment ](url) but ours is deeper. And the encoder part is benefited from pre-computed weights. So in fact it is not fine-tuned from an older textline model.
You can train your own model or fine-tune our model using [https://github.com/qurator-spk/sbb_pixelwise_segmentation](url) .

**Comment by frytoli** [comment]
Thank you!!
