### ISSUE TITLE
Confusing model*dir* variables

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/eynollah#93]
While reviewing the model upload for #91 I read the code again and I still find it confusing to name a variable that contains a filename `model_dir`. Could this be renamed to e.g. `model_file` for clarity? (There are a lot more variables like this in the code - anything `model.*dir.*` probably.)

See also my comment from 2019 here:
https://github.com/qurator-spk/sbb_textline_detection/blob/master/qurator/sbb_textline_detector/main.py#L47
I haven't checked if this is still `image_dir`.

**Comment by bertsky** [comment]
You are right (probably the intended meaning was `model_dir plus submodel xyz`) – but with the proposed change in #91 we actually **do** end up with a directory (TF SavedModel format) again.

**Comment by mikegerber** [comment]
> You are right (probably the intended meaning was `model_dir plus submodel xyz`) – but with the proposed change in #91 we actually **do** end up with a directory (TF SavedModel format) again.

Haha :)
