### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/eynollah#96]
Hi,

I'm having trouble with eynollah 0.0.10 (https://github.com/qurator-spk/ocrd-galley/issues/69) and I noticed that there are a number of commits since that release in 2021 and there's also the eynollah_light feature branch. 

So I was wondering if there will be a new release?

**Comment by kba** [comment]
https://github.com/qurator-spk/eynollah/releases/tag/v0.1.0

**Comment by cneud** [comment]
https://github.com/qurator-spk/eynollah/releases/tag/v0.3.0
